feat: get node ranking api
johnny890122/FINDER_react_frontend pull request #27
Opened 2023-12-16 06:15 UTC by moneychien19

# Issue Link:

https://github.com/johnny890122/FINDER_react_frontend/issues/20

## Feature

- 接 `node_ranking/` api

2023-12-16 06:17 UTC, moneychien19 commented
@johnny890122 我把 `node_ranking/` api 接上了，但是在打的時候會噴錯，再麻煩幫忙看看是怎麼回事了，感謝  

![圖片](https://github.com/johnny890122/FINDER_react_frontend/assets/58811780/03023321-6fa6-4332-8706-aabbb95bfb06)

2023-12-16 10:43 UTC, johnny890122 requested changes

2023-12-16 10:43 UTC, johnny890122 commented on src/pages/game/Game.jsx
> +        body: JSON.stringify({
打 post 的時候，要用 JSON.stringfy()

2023-12-16 10:43 UTC, johnny890122 commented on src/pages/game/Game.jsx
> +          chosen_tool_id: "1",
chosen_tool_id 後端接收是空值，我這邊先用隨便一個數字代替。

2023-12-21 12:46 UTC, moneychien19 commented
@johnny890122 我這邊有推了一個有使用 JSON.stringify 的新版本了，但是還是會有 500 error，連原本可以的 `game_start/` api 都壞了 😮

2023-12-22 06:14 UTC, johnny890122 commented
@moneychien19 我忘記 deploy 我寫完的那版，目前應該修好了。

2023-12-23 15:03 UTC, moneychien19 commented
這樣我這邊前四支 api 都沒問題了

2023-12-24 23:24 UTC, merged